Repository apache/lucene-solr, pull requests merged in 2020-09, with the labels that each got.

#1824 LUCENE-9500: Separate the Deflater hack from the Lucene code to a subclass of java.util.zip.Deflater
  lucene/core/src/java/org/apache/lucene/codecs/lucene87/BugfixDeflater_JDK8252739.java
  lucene/core/src/java/org/apache/lucene/codecs/lucene87/DeflateWithPresetDictCompressionMode.java
  lucene/core/src/test/org/apache/lucene/codecs/lucene87/TestLucene87StoredFieldsFormatHighCompression.java
Labels: bug

#1815 SOLR-14151: Bug fixes
  solr/core/src/java/org/apache/solr/cloud/ZkSolrResourceLoader.java
  solr/core/src/java/org/apache/solr/core/ConfigSetService.java
  solr/core/src/java/org/apache/solr/core/CoreContainer.java
  solr/core/src/java/org/apache/solr/core/SolrCore.java
  solr/core/src/java/org/apache/solr/core/SolrCores.java
  solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java
  solr/core/src/java/org/apache/solr/handler/IndexFetcher.java
  solr/core/src/java/org/apache/solr/handler/SchemaHandler.java
  solr/core/src/java/org/apache/solr/handler/SolrConfigHandler.java
  solr/core/src/java/org/apache/solr/schema/IndexSchema.java
  solr/core/src/java/org/apache/solr/schema/SchemaManager.java
  solr/core/src/test/org/apache/solr/pkg/TestPackages.java
Labels: packages

#1842 LUCENE-9512: Move LockFactory stress test to be a unit/integration test
  gradle/testing/randomization/policies/tests.policy
  lucene/CHANGES.txt
  lucene/core/src/java/org/apache/lucene/store/LockStressTest.java
  lucene/core/src/java/org/apache/lucene/store/LockVerifyServer.java
  lucene/core/src/java/org/apache/lucene/store/VerifyingLockFactory.java
  lucene/core/src/test/org/apache/lucene/store/TestStressLockFactories.java
Labels: enhancement

#1844 SOLR-14847: Create Solr Server TGZ
  help/workflow.txt
  solr/packaging/build.gradle
Labels: build

#1887 SOLR-14875: Make SolrEventListeners load from packages
  solr/CHANGES.txt
  solr/core/src/java/org/apache/solr/core/DelegatingEventListener.java
  solr/core/src/java/org/apache/solr/core/PluginBag.java
  solr/core/src/java/org/apache/solr/core/SolrCore.java
  solr/core/src/java/org/apache/solr/handler/StreamHandler.java
  solr/core/src/java/org/apache/solr/pkg/PackagePluginHolder.java
  solr/core/src/java/org/apache/solr/update/UpdateHandler.java
Labels: packages
