Repository apache/lucene-solr, pull requests merged in 2020-10, with the labels that each got.

#1586 SOLR-14576 : Do not use SolrCore as keys in a WeakHashMap
  solr/CHANGES.txt
  solr/core/src/java/org/apache/solr/servlet/cache/HttpCacheHeaderUtil.java
Labels: perf

#1980 SOLR-14930: Deprecate rulebased replica placement strategy (remove in 9.0)
  solr/CHANGES.txt
  solr/core/src/java/org/apache/solr/cloud/Overseer.java
  solr/core/src/java/org/apache/solr/cloud/api/collections/Assign.java
  solr/core/src/java/org/apache/solr/cloud/api/collections/OverseerCollectionMessageHandler.java
  solr/core/src/java/org/apache/solr/cloud/rule/ImplicitSnitch.java
  solr/core/src/java/org/apache/solr/cloud/rule/ReplicaAssigner.java
  solr/core/src/java/org/apache/solr/cloud/rule/Rule.java
  solr/core/src/java/org/apache/solr/cloud/rule/ServerSnitchContext.java
  solr/core/src/java/org/apache/solr/cloud/rule/package-info.java
  solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java
  solr/core/src/test/org/apache/solr/cloud/rule/ImplicitSnitchTest.java
  solr/core/src/test/org/apache/solr/cloud/rule/RuleEngineTest.java
  solr/core/src/test/org/apache/solr/cloud/rule/RulesTest.java
  solr/core/src/test/org/apache/solr/handler/admin/TestCollectionAPIs.java
  solr/dev-docs/overseer/overseer.adoc
  solr/solr-ref-guide/src/collection-management.adoc
  solr/solr-ref-guide/src/rule-based-replica-placement.adoc
  solr/solr-ref-guide/src/solrcloud.adoc
  solr/solr-ref-guide/src/v2-api.adoc
  solr/solrj/src/java/org/apache/solr/client/solrj/request/CollectionAdminRequest.java
  solr/solrj/src/java/org/apache/solr/common/cloud/DocCollection.java
  solr/solrj/src/resources/apispec/collections.Commands.json
  solr/solrj/src/resources/apispec/collections.collection.Commands.modify.json
Labels: deprecation

#1988 SOLR-14483
  solr/CHANGES.txt
  solr/webapp/web/css/angular/collections.css
  solr/webapp/web/js/angular/controllers/collections.js
  solr/webapp/web/partials/collections.html
Labels: hacktoberfest-accepted

#1984 SOLR-14930: Deprecate rulebased replica placement strategy(in 8.x)
  solr/CHANGES.txt
  solr/core/src/java/org/apache/solr/cloud/rule/ImplicitSnitch.java
  solr/core/src/java/org/apache/solr/cloud/rule/ReplicaAssigner.java
  solr/core/src/java/org/apache/solr/cloud/rule/Rule.java
  solr/core/src/java/org/apache/solr/cloud/rule/ServerSnitchContext.java
  solr/solr-ref-guide/src/rule-based-replica-placement.adoc
  solr/solrj/src/java/org/apache/solr/common/cloud/DocCollection.java
Labels: deprecation

#2039 LUCENE-9587: Add '--illegal-access=deny' to test runner
  gradle/testing/defaults-tests.gradle
Labels: test-fix
