Repository apache/lucene-solr, pull requests merged in 2020-07, with the labels that each got.

#1541 RegExp - add case insensitive matching option
  lucene/core/src/java/org/apache/lucene/search/RegexpQuery.java
  lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java
  lucene/core/src/test/org/apache/lucene/search/TestRegexpQuery.java
  lucene/core/src/test/org/apache/lucene/util/automaton/TestRegExp.java
Labels: enhancement

#1658 LUCENE-9423: Handle exception in NIOFSDirectory#openInput
  lucene/core/src/java/org/apache/lucene/store/NIOFSDirectory.java
  lucene/core/src/test/org/apache/lucene/store/TestNIOFSDirectory.java
Labels: bug

#1669 SOLR-14151 Make schema components load from packages
  solr/CHANGES.txt
  solr/core/src/java/org/apache/solr/api/CustomContainerPlugins.java
  solr/core/src/java/org/apache/solr/core/ConfigSet.java
  solr/core/src/java/org/apache/solr/core/ConfigSetService.java
  solr/core/src/java/org/apache/solr/core/CoreContainer.java
  solr/core/src/java/org/apache/solr/core/PluginBag.java
  solr/core/src/java/org/apache/solr/core/PluginInfo.java
  solr/core/src/java/org/apache/solr/core/SolrClassLoader.java
  solr/core/src/java/org/apache/solr/core/SolrConfig.java
  solr/core/src/java/org/apache/solr/core/SolrCore.java
  solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java
  solr/core/src/java/org/apache/solr/handler/SchemaHandler.java
  solr/core/src/java/org/apache/solr/handler/SolrConfigHandler.java
  solr/core/src/java/org/apache/solr/handler/StreamHandler.java
  solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
  solr/core/src/java/org/apache/solr/packagemanager/PackageManager.java
  solr/core/src/java/org/apache/solr/packagemanager/RepositoryManager.java
  solr/core/src/java/org/apache/solr/pkg/PackageAPI.java
  solr/core/src/java/org/apache/solr/pkg/PackageListeners.java
  solr/core/src/java/org/apache/solr/pkg/PackageListeningClassLoader.java
  solr/core/src/java/org/apache/solr/pkg/PackageLoader.java
  solr/core/src/java/org/apache/solr/pkg/PackagePluginHolder.java
  solr/core/src/java/org/apache/solr/schema/FieldTypePluginLoader.java
  solr/core/src/java/org/apache/solr/schema/IndexSchema.java
  solr/core/src/java/org/apache/solr/schema/ManagedIndexSchema.java
  solr/core/src/java/org/apache/solr/schema/PreAnalyzedField.java
  solr/core/src/java/org/apache/solr/util/plugin/AbstractPluginLoader.java
  solr/core/src/test-files/runtimecode/schema-plugins.jar.bin
  solr/core/src/test-files/runtimecode/sig.txt
  solr/core/src/test/org/apache/solr/core/TestCodecSupport.java
  solr/core/src/test/org/apache/solr/pkg/TestPackages.java
Labels: packages
